  
version: '3'
services:
  wiremock:
    build: .
    image: lgvalle/wiremock
    container_name: wiremock-standalone
    ports: 
      - "8080:8080"
    volumes:
      - ./mappings:/var/wiremock/mappings